# Generated by Django 5.0 on 2024-01-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('MentorID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('MentorName', models.TextField(max_length=20)),
                ('RoomNo', models.IntegerField(max_length=4)),
            ],
        ),
    ]
